// "De 1 usuario a millones": adaptado de system-design-primer (Donne Martin, CC BY 4.0),
// solución "Design a system that scales to millions of users on AWS".
import type { Escenario } from '../tipos';

const S3 = { s1: { x: 420, y: 170 }, s2: { x: 420, y: 260, from: 's1' }, s3: { x: 420, y: 350, from: 's1' } };
// Los servidores no se conectan uno a uno con cada almacén: pasan por un punto interno
// (el balanceador interno que el primer omite), así el dibujo no se vuelve una telaraña.
const J = { x: 520, y: 260 };
const viaJ = (dest: string[], servers = ['s1', 's2', 's3']) => [...servers.map((s) => `${s}>j`), ...dest.map((d) => `j>${d}`)];

const lecturasConCache = [
	{ camino: ['user', 'lb', 'S', 'j', 'cache'], peso: 0.5, tipo: 'lectura' as const },
	{ camino: ['user', 'lb', 'S', 'j', 'R'], peso: 0.2, tipo: 'lectura' as const },
	{ camino: ['user', 'lb', 'S', 'j', 'db'], peso: 0.06, tipo: 'escritura' as const },
	{ camino: ['user', 'cdn'], peso: 0.24, tipo: 'estatico' as const },
];

export const escalar: Escenario = {
	viewBox: [840, 500],
	leyenda: {
		lectura: { es: 'lectura', en: 'read' },
		escritura: { es: 'escritura', en: 'write' },
		estatico: { es: 'archivo estático', en: 'static file' },
		async: { es: 'tarea en segundo plano', en: 'background job' },
	},
	nodos: {
		user: { label: { es: 'Usuarios', en: 'Users' }, kind: 'user' },
		j: { label: { es: 'red interna', en: 'internal network' }, kind: 'punto' },
		dns: { label: { es: 'DNS', en: 'DNS' }, sub: { es: 'nombre → IP', en: 'name → IP' } },
		lb: { label: { es: 'Balanceador', en: 'Load balancer' }, sub: { es: 'reparte y termina TLS', en: 'spreads load, ends TLS' } },
		cdn: { label: { es: 'CDN', en: 'CDN' }, sub: { es: 'estáticos cerca del usuario', en: 'static near the user' } },
		s1: { label: { es: 'Servidor', en: 'Server' } },
		s2: { label: { es: 'Servidor', en: 'Server' }, sub: { es: 'web + app', en: 'web + app' } },
		s3: { label: { es: 'Servidor', en: 'Server' }, sub: { es: 'web + app', en: 'web + app' } },
		s4: { label: { es: 'Servidor', en: 'Server' }, sub: { es: 'autoescalado', en: 'autoscaled' } },
		s5: { label: { es: 'Servidor', en: 'Server' }, sub: { es: 'autoescalado', en: 'autoscaled' } },
		cache: { label: { es: 'Caché en memoria', en: 'Memory cache' }, sub: { es: 'datos calientes y sesiones', en: 'hot data and sessions' }, kind: 'store' },
		obj: { label: { es: 'Almacén de objetos', en: 'Object store' }, sub: { es: 'imágenes, JS, CSS', en: 'images, JS, CSS' }, kind: 'store' },
		queue: { label: { es: 'Cola', en: 'Queue' }, sub: { es: 'trabajo diferido', en: 'deferred work' } },
		workers: { label: { es: 'Workers', en: 'Workers' }, sub: { es: 'ej. miniaturas', en: 'e.g. thumbnails' } },
		db: { label: { es: 'Base de datos', en: 'Database' }, sub: { es: 'SQL', en: 'SQL' }, kind: 'store' },
		standby: { label: { es: 'Réplica en espera', en: 'Standby replica' }, sub: { es: 'failover', en: 'failover' }, kind: 'store' },
		r1: { label: { es: 'Réplica de lectura', en: 'Read replica' }, kind: 'store' },
		r2: { label: { es: 'Réplica de lectura', en: 'Read replica' }, kind: 'store' },
	},
	etapas: [
		{
			hud: { es: '1 usuario', en: '1 user' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				s1: { x: 420, y: 260, sub: { es: 'web + app + BD', en: 'web + app + DB' } },
			},
			aristas: ['user>dns~', 'user>s1'],
			rutas: [
				{ camino: ['user', 's1'], peso: 0.9, tipo: 'lectura' },
				{ camino: ['user', 's1'], peso: 0.1, tipo: 'escritura' },
			],
			cada: 1100,
			cuello: { nodo: 's1', nota: { es: 'CPU y memoria al límite', en: 'CPU and memory maxed out' } },
		},
		{
			hud: { es: 'Usuarios+', en: 'Users+' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				s1: { x: 420, y: 260, sub: { es: 'web + app', en: 'web + app' } },
				db: { x: 770, y: 260, from: 's1' },
				obj: { x: 605, y: 440, from: 's1' },
			},
			aristas: ['user>dns~', 'user>s1', 's1>db', 'user>obj'],
			rutas: [
				{ camino: ['user', 's1', 'db'], peso: 0.6, tipo: 'lectura' },
				{ camino: ['user', 's1', 'db'], peso: 0.1, tipo: 'escritura' },
				{ camino: ['user', 'obj'], peso: 0.3, tipo: 'estatico' },
			],
			cada: 700,
			cuello: { nodo: 's1', nota: { es: 'un solo servidor: se cae en horas pico', en: 'one server: falls over at peak' } },
		},
		{
			hud: { es: 'Usuarios++', en: 'Users++' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				lb: { x: 235, y: 260 },
				j: J,
				cdn: { x: 235, y: 440 },
				...S3,
				s1: { x: 420, y: 170, sub: { es: 'web + app', en: 'web + app' } },
				db: { x: 770, y: 250, sub: { es: 'principal', en: 'primary' } },
				standby: { x: 770, y: 345, from: 'db', dashed: true },
				obj: { x: 605, y: 440 },
			},
			aristas: ['user>dns~', 'user>lb', 'lb>s1', 'lb>s2', 'lb>s3', ...viaJ(['db']), 'db>standby~', 'user>cdn', 'cdn>obj'],
			rutas: [
				{ camino: ['user', 'lb', 'S', 'j', 'db'], peso: 0.6, tipo: 'lectura' },
				{ camino: ['user', 'lb', 'S', 'j', 'db'], peso: 0.08, tipo: 'escritura' },
				{ camino: ['user', 'cdn'], peso: 0.25, tipo: 'estatico' },
				{ camino: ['user', 'cdn', 'obj'], peso: 0.07, tipo: 'estatico' },
			],
			cada: 420,
			cuello: { nodo: 'db', nota: { es: '100 lecturas por escritura: la BD no da abasto', en: '100 reads per write: the DB can’t keep up' } },
		},
		{
			hud: { es: 'Usuarios+++', en: 'Users+++' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				lb: { x: 235, y: 260 },
				j: J,
				cdn: { x: 235, y: 440 },
				...S3,
				s1: { x: 420, y: 170, sub: { es: 'web + app, sin estado', en: 'web + app, stateless' } },
				cache: { x: 605, y: 110 },
				db: { x: 770, y: 250, sub: { es: 'principal: escrituras', en: 'primary: writes' } },
				standby: { x: 770, y: 345, dashed: true },
				r1: { x: 770, y: 160, from: 'db' },
				r2: { x: 770, y: 70, from: 'db' },
				obj: { x: 605, y: 440 },
			},
			aristas: ['user>dns~', 'user>lb', 'lb>s1', 'lb>s2', 'lb>s3', ...viaJ(['cache', 'r1', 'r2', 'db']), 'db>standby~', 'db>r1~', 'db>r2~', 'user>cdn', 'cdn>obj'],
			rutas: lecturasConCache,
			cada: 260,
			cuello: { nodo: 'lb', nota: { es: 'picos de día, valles de noche: pagas servidores ociosos', en: 'daytime peaks, idle servers at night' } },
		},
		{
			hud: { es: 'Usuarios++++', en: 'Users++++' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				lb: { x: 235, y: 260 },
				j: J,
				cdn: { x: 235, y: 440 },
				s1: { x: 420, y: 80, sub: { es: 'web + app, sin estado', en: 'web + app, stateless' } },
				s2: { x: 420, y: 170 },
				s3: { x: 420, y: 260 },
				s4: { x: 420, y: 350, from: 's3' },
				s5: { x: 420, y: 440, from: 's3' },
				cache: { x: 605, y: 110 },
				db: { x: 770, y: 250, sub: { es: 'principal: escrituras', en: 'primary: writes' } },
				standby: { x: 770, y: 345, dashed: true },
				r1: { x: 770, y: 160 },
				r2: { x: 770, y: 70 },
				obj: { x: 605, y: 440 },
			},
			aristas: [
				'user>dns~', 'user>lb', 'lb>s1', 'lb>s2', 'lb>s3', 'lb>s4', 'lb>s5',
				...viaJ(['cache', 'r1', 'r2', 'db'], ['s1', 's2', 's3', 's4', 's5']),
				'db>standby~', 'db>r1~', 'db>r2~', 'user>cdn', 'cdn>obj',
			],
			rutas: lecturasConCache,
			cada: 170,
			respiran: ['s4', 's5'],
			cuello: { nodo: 'db', nota: { es: 'escrituras y volumen: una sola BD principal ya no alcanza', en: 'writes and size: one primary is not enough' } },
		},
		{
			hud: { es: '10 M usuarios · 40.000 lecturas/s · 400 escrituras/s', en: '10 M users · 40,000 reads/s · 400 writes/s' },
			nodos: {
				user: { x: 70, y: 260 },
				dns: { x: 235, y: 70 },
				lb: { x: 235, y: 260 },
				j: J,
				cdn: { x: 235, y: 440 },
				...S3,
				s1: { x: 420, y: 170, sub: { es: 'grupos con autoescalado', en: 'autoscaling groups' } },
				cache: { x: 605, y: 110 },
				queue: { x: 605, y: 330, from: 's3' },
				workers: { x: 770, y: 440, from: 'queue' },
				db: { x: 770, y: 250, sub: { es: 'sharding / NoSQL', en: 'sharding / NoSQL' } },
				standby: { x: 770, y: 345, dashed: true },
				r1: { x: 770, y: 160 },
				r2: { x: 770, y: 70 },
				obj: { x: 605, y: 440 },
			},
			aristas: [
				'user>dns~', 'user>lb', 'lb>s1', 'lb>s2', 'lb>s3', ...viaJ(['cache', 'r1', 'r2', 'db', 'queue']),
				'db>standby~', 'db>r1~', 'db>r2~', 'user>cdn', 'cdn>obj', 'queue>workers', 'workers>obj', 'workers>db',
			],
			rutas: [...lecturasConCache.map((r) => ({ ...r, peso: r.peso * 0.92 })), { camino: ['user', 'lb', 'S', 'j', 'queue', 'workers', 'obj'], peso: 0.08, tipo: 'async' }],
			cada: 140,
		},
	],
};
